kind: ConfigMap
apiVersion: v1
metadata:
  name: overprovisioning-autoscaler-v2
  namespace: hpa
data:
  linear: |-
    { 
      "nodesPerReplica": 1,
      "min":1,
      "max":10,
      "includeUnschedulableNodes": true
    }

##coresPerReplica: One pause pod per core, meaning one pause pod for each core.
##nodesPerReplica: One pause pod per node, signifying one pause pod for each node.
